"use client";

import { useState } from "react";
import { ShieldCheck, KeyRound, Loader2, ArrowLeft, ArrowRight } from "lucide-react";
import { toast } from "sonner";

interface TwoFactorVerifyModalProps {
  isLoading: boolean;
  onVerify: (code: string) => Promise<void>;
  onBackToLogin: () => void;
}

export function TwoFactorVerifyModal({
  isLoading,
  onVerify,
  onBackToLogin,
}: TwoFactorVerifyModalProps) {
  const [code, setCode] = useState("");
  const [useRecoveryCode, setUseRecoveryCode] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!code.trim()) {
      toast.error(useRecoveryCode ? "Please enter a recovery code" : "Please enter your 6-digit code");
      return;
    }
    if (!useRecoveryCode && code.trim().length !== 6) {
      toast.error("Please enter a 6-digit code");
      return;
    }
    await onVerify(code.trim());
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="text-center space-y-1">
        <div className="mx-auto w-12 h-12 rounded-full bg-[#02B2FF]/10 text-[#02B2FF] flex items-center justify-center mb-3">
          {useRecoveryCode ? <KeyRound className="w-6 h-6" /> : <ShieldCheck className="w-6 h-6" />}
        </div>
        <h2 className="text-xl font-bold text-foreground">
          {useRecoveryCode ? "Enter Backup Recovery Code" : "Two-Factor Authentication"}
        </h2>
        <p className="text-sm text-muted-foreground">
          {useRecoveryCode
            ? "Enter one of your 10-character recovery codes (e.g. XXXX-XXXX)."
            : "Enter the 6-digit code generated by your authenticator app."}
        </p>
      </div>

      {/* Verification Form */}
      <form onSubmit={handleSubmit} className="space-y-5">
        <div>
          <label className="block text-sm font-medium text-foreground mb-1 text-center">
            {useRecoveryCode ? "Recovery Code" : "6-Digit Authenticator Code"}
          </label>
          <input
            type="text"
            inputMode={useRecoveryCode ? "text" : "numeric"}
            pattern={useRecoveryCode ? undefined : "[0-9]*"}
            maxLength={useRecoveryCode ? 12 : 6}
            value={code}
            onChange={(e) => {
              if (useRecoveryCode) {
                setCode(e.target.value.toUpperCase());
              } else {
                setCode(e.target.value.replace(/\D/g, ""));
              }
            }}
            placeholder={useRecoveryCode ? "XXXX-XXXX" : "000000"}
            className={`w-full text-center font-mono font-bold px-4 py-3 border border-border rounded-xl focus:outline-none focus:ring-2 focus:ring-[#02B2FF] focus:border-transparent bg-background ${
              useRecoveryCode ? "text-xl tracking-widest" : "text-3xl tracking-[0.4em]"
            }`}
            autoFocus
            disabled={isLoading}
          />
        </div>

        {/* Mode Toggle Link */}
        <div className="text-center">
          <button
            type="button"
            onClick={() => {
              setUseRecoveryCode(!useRecoveryCode);
              setCode("");
            }}
            className="text-xs text-[#02B2FF] hover:underline font-medium"
          >
            {useRecoveryCode
              ? "Use 6-digit authenticator code instead"
              : "Lost access to authenticator? Use a recovery code"}
          </button>
        </div>

        {/* Actions */}
        <div className="space-y-3 pt-2">
          <button
            type="submit"
            disabled={isLoading || !code.trim()}
            className="w-full bg-[#02B2FF] hover:bg-[#0290d6] text-white font-medium py-3 rounded-xl transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 text-sm shadow-md shadow-[#02B2FF]/20"
          >
            {isLoading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Verifying...
              </>
            ) : (
              <>
                Verify & Sign In
                <ArrowRight className="w-4 h-4" />
              </>
            )}
          </button>

          <button
            type="button"
            onClick={onBackToLogin}
            disabled={isLoading}
            className="w-full flex items-center justify-center gap-2 py-2.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back to login with username & password
          </button>
        </div>
      </form>
    </div>
  );
}
